# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.12.0

pipelines:
  branches:
    dev:
        - step:
            deployment: staging
            name: Generate Static Files
            caches:
              - node
            script:
              - npm install
            artifacts:
              - dist/*
              - dist/**/*
              - dist/**/**
        - step:
            name: Deploy to S3 for development env
            image: atlassian/pipelines-awscli
            script: 
              - aws s3 sync --acl public-read --delete ./dist s3://$S3_BUCKET_NAME
    testing:
        - step:
            deployment: development
            name: Generate Static Files
            script:
              - npm install
            artifacts:
              - dist/*
              - dist/**/*
              - dist/**/**
        - step:
            name: Deploy to S3 for testing env
            image: atlassian/pipelines-awscli
            script: 
              - aws s3 sync --acl public-read --delete ./dist s3://$S3_BUCKET_NAME
    staging:
        - step:
            deployment: staging
            name: Generate Static Files
            script:
              - npm install
            artifacts:
              - dist/*
              - dist/**/*
              - dist/**/**
        - step:
            name: Deploy to S3 for staging env
            image: atlassian/pipelines-awscli
            script: 
              - aws s3 sync --acl public-read --delete ./dist s3://$S3_BUCKET_NAME
    master:
        - step:
            deployment: production
            name: Generate Static Files
            script:
              - npm install
            artifacts:
              - dist/*
              - dist/**/*
              - dist/**/**
        - step:
            name: Deploy to S3 for production
            image: atlassian/pipelines-awscli
            script: 
              - aws s3 sync --acl public-read --delete ./dist s3://$S3_BUCKET_NAME
